services:
  web:
    build: .
    image: ibkr-rest-api
    container_name: ibkr
    environment:
      IBKR_ACCOUNT_ID: "DUA732142"
    ports:
      - "5000:5000"
      - "5056:5056"
    volumes:
      - ./webapp:/app/webapp
